package com.hz.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.hz.greendao.dao.GeologicalConditionType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GEOLOGICAL_CONDITION_TYPE".
*/
public class GeologicalConditionTypeDao extends AbstractDao<GeologicalConditionType, Long> {

    public static final String TABLENAME = "GEOLOGICAL_CONDITION_TYPE";

    /**
     * Properties of entity GeologicalConditionType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property SoilType = new Property(1, String.class, "soilType", false, "SOIL_TYPE");
        public final static Property Scbz = new Property(2, String.class, "scbz", false, "SCBZ");
        public final static Property Cjsj = new Property(3, java.util.Date.class, "cjsj", false, "CJSJ");
        public final static Property UpdateDate = new Property(4, java.util.Date.class, "updateDate", false, "UPDATE_DATE");
    };


    public GeologicalConditionTypeDao(DaoConfig config) {
        super(config);
    }
    
    public GeologicalConditionTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GEOLOGICAL_CONDITION_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"SOIL_TYPE\" TEXT," + // 1: soilType
                "\"SCBZ\" TEXT," + // 2: scbz
                "\"CJSJ\" INTEGER," + // 3: cjsj
                "\"UPDATE_DATE\" INTEGER);"); // 4: updateDate
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_GEOLOGICAL_CONDITION_TYPE__id ON GEOLOGICAL_CONDITION_TYPE" +
                " (\"_id\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GEOLOGICAL_CONDITION_TYPE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GeologicalConditionType entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String soilType = entity.getSoilType();
        if (soilType != null) {
            stmt.bindString(2, soilType);
        }
 
        String scbz = entity.getScbz();
        if (scbz != null) {
            stmt.bindString(3, scbz);
        }
 
        java.util.Date cjsj = entity.getCjsj();
        if (cjsj != null) {
            stmt.bindLong(4, cjsj.getTime());
        }
 
        java.util.Date updateDate = entity.getUpdateDate();
        if (updateDate != null) {
            stmt.bindLong(5, updateDate.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GeologicalConditionType readEntity(Cursor cursor, int offset) {
        GeologicalConditionType entity = new GeologicalConditionType( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // soilType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // scbz
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // cjsj
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)) // updateDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GeologicalConditionType entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setSoilType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setScbz(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCjsj(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setUpdateDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GeologicalConditionType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GeologicalConditionType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
