package com.hz.greendao.dao;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MAP_LINE_ENTITY".
 */
public class MapLineEntity implements java.io.Serializable {

    public String getTag() {
        if(tag == null){
            return "";
        }
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * Not-null value.
     */
    private String tag;
    private String lineId;
    private long lineProjId;
    private long lineUserId;
    private int lineEditType;
    private int lineType;
    private String lineName;
    private String lineNote;
    private int lineRemoved;
    private boolean lineNeedToUpload;
    private double lineStartLatitude;
    private double lineStartLongitude;
    private double lineEndLatitude;
    private double lineEndLongitude;
    private String lineWireTypeId;
    private String lineStartPointId;
    private String lineEndPointId;
    private String lineStartPointName;
    private String lineEndPointName;
    private Double lineLength;
    private int lineSpecificationNumber;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient MapLineEntityDao myDao;

    private List<MapLineItemEntity> mapLineItemEntityList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MapLineEntity() {
    }

    public MapLineEntity(String lineId) {
        this.lineId = lineId;
    }

    public MapLineEntity(String lineId, long lineProjId, long lineUserId, int lineEditType, int lineType, String lineName, String lineNote, int lineRemoved, boolean lineNeedToUpload, double lineStartLatitude, double lineStartLongitude, double lineEndLatitude, double lineEndLongitude, String lineWireTypeId, String lineStartPointId, String lineEndPointId, String lineStartPointName, String lineEndPointName, Double lineLength, int lineSpecificationNumber) {
        this.lineId = lineId;
        this.lineProjId = lineProjId;
        this.lineUserId = lineUserId;
        this.lineEditType = lineEditType;
        this.lineType = lineType;
        this.lineName = lineName;
        this.lineNote = lineNote;
        this.lineRemoved = lineRemoved;
        this.lineNeedToUpload = lineNeedToUpload;
        this.lineStartLatitude = lineStartLatitude;
        this.lineStartLongitude = lineStartLongitude;
        this.lineEndLatitude = lineEndLatitude;
        this.lineEndLongitude = lineEndLongitude;
        this.lineWireTypeId = lineWireTypeId;
        this.lineStartPointId = lineStartPointId;
        this.lineEndPointId = lineEndPointId;
        this.lineStartPointName = lineStartPointName;
        this.lineEndPointName = lineEndPointName;
        this.lineLength = lineLength;
        this.lineSpecificationNumber = lineSpecificationNumber;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMapLineEntityDao() : null;
    }

    /**
     * Not-null value.
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setLineId(String lineId) {
        this.lineId = lineId;
    }

    public long getLineProjId() {
        return lineProjId;
    }

    public void setLineProjId(long lineProjId) {
        this.lineProjId = lineProjId;
    }

    public long getLineUserId() {
        return lineUserId;
    }

    public void setLineUserId(long lineUserId) {
        this.lineUserId = lineUserId;
    }

    public int getLineEditType() {
        return lineEditType;
    }

    public void setLineEditType(int lineEditType) {
        this.lineEditType = lineEditType;
    }

    public int getLineType() {
        return lineType;
    }

    public void setLineType(int lineType) {
        this.lineType = lineType;
    }

    public String getLineName() {
        return lineName;
    }

    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    public String getLineNote() {
        return lineNote;
    }

    public void setLineNote(String lineNote) {
        this.lineNote = lineNote;
    }

    public int getLineRemoved() {
        return lineRemoved;
    }

    public void setLineRemoved(int lineRemoved) {
        this.lineRemoved = lineRemoved;
    }

    public boolean getLineNeedToUpload() {
        return lineNeedToUpload;
    }

    public void setLineNeedToUpload(boolean lineNeedToUpload) {
        this.lineNeedToUpload = lineNeedToUpload;
    }

    public double getLineStartLatitude() {
        return lineStartLatitude;
    }

    public void setLineStartLatitude(double lineStartLatitude) {
        this.lineStartLatitude = lineStartLatitude;
    }

    public double getLineStartLongitude() {
        return lineStartLongitude;
    }

    public void setLineStartLongitude(double lineStartLongitude) {
        this.lineStartLongitude = lineStartLongitude;
    }

    public double getLineEndLatitude() {
        return lineEndLatitude;
    }

    public void setLineEndLatitude(double lineEndLatitude) {
        this.lineEndLatitude = lineEndLatitude;
    }

    public double getLineEndLongitude() {
        return lineEndLongitude;
    }

    public void setLineEndLongitude(double lineEndLongitude) {
        this.lineEndLongitude = lineEndLongitude;
    }

    public String getLineWireTypeId() {
        return lineWireTypeId;
    }

    public void setLineWireTypeId(String lineWireTypeId) {
        this.lineWireTypeId = lineWireTypeId;
    }

    public String getLineStartPointId() {
        return lineStartPointId;
    }

    public void setLineStartPointId(String lineStartPointId) {
        this.lineStartPointId = lineStartPointId;
    }

    public String getLineEndPointId() {
        return lineEndPointId;
    }

    public void setLineEndPointId(String lineEndPointId) {
        this.lineEndPointId = lineEndPointId;
    }

    public String getLineStartPointName() {
        return lineStartPointName;
    }

    public void setLineStartPointName(String lineStartPointName) {
        this.lineStartPointName = lineStartPointName;
    }

    public String getLineEndPointName() {
        return lineEndPointName;
    }

    public void setLineEndPointName(String lineEndPointName) {
        this.lineEndPointName = lineEndPointName;
    }

    public Double getLineLength() {
        return lineLength;
    }

    public void setLineLength(Double lineLength) {
        this.lineLength = lineLength;
    }

    public int getLineSpecificationNumber() {
        return lineSpecificationNumber;
    }

    public void setLineSpecificationNumber(int lineSpecificationNumber) {
        this.lineSpecificationNumber = lineSpecificationNumber;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<MapLineItemEntity> getMapLineItemEntityList() {
        if (mapLineItemEntityList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MapLineItemEntityDao targetDao = daoSession.getMapLineItemEntityDao();
            List<MapLineItemEntity> mapLineItemEntityListNew = targetDao._queryMapLineEntity_MapLineItemEntityList(lineId);
            synchronized (this) {
                if (mapLineItemEntityList == null) {
                    mapLineItemEntityList = mapLineItemEntityListNew;
                }
            }
        }
        return mapLineItemEntityList;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetMapLineItemEntityList() {
        mapLineItemEntityList = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here

    public void setMapLineItemEntityList(List<MapLineItemEntity> mapLineItemEntityList) {
        this.mapLineItemEntityList = mapLineItemEntityList;
    }

    public List<MapLineItemEntity> getMapLineItemEntityList2() {
        return this.mapLineItemEntityList;
    }

    @Override
    public String toString() {
        return "MapLineEntity{" +
                "lineId='" + lineId + '\'' +
                ", lineProjId=" + lineProjId +
                ", lineUserId=" + lineUserId +
                ", lineEditType=" + lineEditType +
                ", lineType=" + lineType +
                ", lineName='" + lineName + '\'' +
                ", lineNote='" + lineNote + '\'' +
                ", lineRemoved=" + lineRemoved +
                ", lineNeedToUpload=" + lineNeedToUpload +
                ", lineStartLatitude=" + lineStartLatitude +
                ", lineStartLongitude=" + lineStartLongitude +
                ", lineEndLatitude=" + lineEndLatitude +
                ", lineEndLongitude=" + lineEndLongitude +
                ", lineWireTypeId='" + lineWireTypeId + '\'' +
                ", lineStartPointId='" + lineStartPointId + '\'' +
                ", lineEndPointId='" + lineEndPointId + '\'' +
                ", lineStartPointName='" + lineStartPointName + '\'' +
                ", lineEndPointName='" + lineEndPointName + '\'' +
                ", lineLength=" + lineLength +
                ", lineSpecificationNumber=" + lineSpecificationNumber +
                ", daoSession=" + daoSession +
                ", myDao=" + myDao +
                ", mapLineItemEntityList=" + mapLineItemEntityList +
                '}';
    }

    // KEEP METHODS END

}
