package com.hz.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.List;
// KEEP INCLUDES END
/**
 * Entity mapped to table "MAP_POI_ENTITY".
 */
public class MapPoiEntity implements java.io.Serializable {

    /** Not-null value. */
    private String pointId;
    private long pointProjId;
    private long pointUserId;
    private int pointEditType;
    private int pointType;
    private double pointLatitude;
    private double pointLongitude;
    private String pointName;
    private String pointNote;
    private int pointRemoved;
    private boolean pointNeedToUpload;
    /** Not-null value. */
    private java.util.Date pointUpdateDate;
    private int pointLightingNum;
    private int pointPowerNum;
    private int pointConnectDoorNum;
    private String pointTransformerTypeId;
    private int pointStatus;
    private String pointTowerTypeId;
    private String pointGeologicalConditionsTypeId;
    private String pointEquipmentInstallationTypeId;
    private String pointElectricPoleTypeId;
    private int pointElectricPoleTypeCount;
    private String pointLandForm;
    private String pointNum;
    private Double pointCoverDepth;

    // KEEP FIELDS - put your custom fields here

    /**
     * 点位关联图片路径
     */
    @JsonIgnore
    public List<PointGalleryEntity> pointGalleryLists;
    // KEEP FIELDS END

    public MapPoiEntity() {
    }

    public MapPoiEntity(String pointId) {
        this.pointId = pointId;
    }

    public MapPoiEntity(String pointId, long pointProjId, long pointUserId, int pointEditType, int pointType, double pointLatitude, double pointLongitude, String pointName, String pointNote, int pointRemoved, boolean pointNeedToUpload, java.util.Date pointUpdateDate, int pointLightingNum, int pointPowerNum, int pointConnectDoorNum, String pointTransformerTypeId, int pointStatus, String pointTowerTypeId, String pointGeologicalConditionsTypeId, String pointEquipmentInstallationTypeId, String pointElectricPoleTypeId, int pointElectricPoleTypeCount, String pointLandForm, String pointNum, Double pointCoverDepth) {
        this.pointId = pointId;
        this.pointProjId = pointProjId;
        this.pointUserId = pointUserId;
        this.pointEditType = pointEditType;
        this.pointType = pointType;
        this.pointLatitude = pointLatitude;
        this.pointLongitude = pointLongitude;
        this.pointName = pointName;
        this.pointNote = pointNote;
        this.pointRemoved = pointRemoved;
        this.pointNeedToUpload = pointNeedToUpload;
        this.pointUpdateDate = pointUpdateDate;
        this.pointLightingNum = pointLightingNum;
        this.pointPowerNum = pointPowerNum;
        this.pointConnectDoorNum = pointConnectDoorNum;
        this.pointTransformerTypeId = pointTransformerTypeId;
        this.pointStatus = pointStatus;
        this.pointTowerTypeId = pointTowerTypeId;
        this.pointGeologicalConditionsTypeId = pointGeologicalConditionsTypeId;
        this.pointEquipmentInstallationTypeId = pointEquipmentInstallationTypeId;
        this.pointElectricPoleTypeId = pointElectricPoleTypeId;
        this.pointElectricPoleTypeCount = pointElectricPoleTypeCount;
        this.pointLandForm = pointLandForm;
        this.pointNum = pointNum;
        this.pointCoverDepth = pointCoverDepth;
    }

    /** Not-null value. */
    public String getPointId() {
        return pointId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPointId(String pointId) {
        this.pointId = pointId;
    }

    public long getPointProjId() {
        return pointProjId;
    }

    public void setPointProjId(long pointProjId) {
        this.pointProjId = pointProjId;
    }

    public long getPointUserId() {
        return pointUserId;
    }

    public void setPointUserId(long pointUserId) {
        this.pointUserId = pointUserId;
    }

    public int getPointEditType() {
        return pointEditType;
    }

    public void setPointEditType(int pointEditType) {
        this.pointEditType = pointEditType;
    }

    public int getPointType() {
        return pointType;
    }

    public void setPointType(int pointType) {
        this.pointType = pointType;
    }

    public double getPointLatitude() {
        return pointLatitude;
    }

    public void setPointLatitude(double pointLatitude) {
        this.pointLatitude = pointLatitude;
    }

    public double getPointLongitude() {
        return pointLongitude;
    }

    public void setPointLongitude(double pointLongitude) {
        this.pointLongitude = pointLongitude;
    }

    public String getPointName() {
        return pointName;
    }

    public void setPointName(String pointName) {
        this.pointName = pointName;
    }

    public String getPointNote() {
        return pointNote;
    }

    public void setPointNote(String pointNote) {
        this.pointNote = pointNote;
    }

    public int getPointRemoved() {
        return pointRemoved;
    }

    public void setPointRemoved(int pointRemoved) {
        this.pointRemoved = pointRemoved;
    }

    public boolean getPointNeedToUpload() {
        return pointNeedToUpload;
    }

    public void setPointNeedToUpload(boolean pointNeedToUpload) {
        this.pointNeedToUpload = pointNeedToUpload;
    }

    /** Not-null value. */
    public java.util.Date getPointUpdateDate() {
        return pointUpdateDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPointUpdateDate(java.util.Date pointUpdateDate) {
        this.pointUpdateDate = pointUpdateDate;
    }

    public int getPointLightingNum() {
        return pointLightingNum;
    }

    public void setPointLightingNum(int pointLightingNum) {
        this.pointLightingNum = pointLightingNum;
    }

    public int getPointPowerNum() {
        return pointPowerNum;
    }

    public void setPointPowerNum(int pointPowerNum) {
        this.pointPowerNum = pointPowerNum;
    }

    public int getPointConnectDoorNum() {
        return pointConnectDoorNum;
    }

    public void setPointConnectDoorNum(int pointConnectDoorNum) {
        this.pointConnectDoorNum = pointConnectDoorNum;
    }

    public String getPointTransformerTypeId() {
        return pointTransformerTypeId;
    }

    public void setPointTransformerTypeId(String pointTransformerTypeId) {
        this.pointTransformerTypeId = pointTransformerTypeId;
    }

    public int getPointStatus() {
        return pointStatus;
    }

    public void setPointStatus(int pointStatus) {
        this.pointStatus = pointStatus;
    }

    public String getPointTowerTypeId() {
        return pointTowerTypeId;
    }

    public void setPointTowerTypeId(String pointTowerTypeId) {
        this.pointTowerTypeId = pointTowerTypeId;
    }

    public String getPointGeologicalConditionsTypeId() {
        return pointGeologicalConditionsTypeId;
    }

    public void setPointGeologicalConditionsTypeId(String pointGeologicalConditionsTypeId) {
        this.pointGeologicalConditionsTypeId = pointGeologicalConditionsTypeId;
    }

    public String getPointEquipmentInstallationTypeId() {
        return pointEquipmentInstallationTypeId;
    }

    public void setPointEquipmentInstallationTypeId(String pointEquipmentInstallationTypeId) {
        this.pointEquipmentInstallationTypeId = pointEquipmentInstallationTypeId;
    }

    public String getPointElectricPoleTypeId() {
        return pointElectricPoleTypeId;
    }

    public void setPointElectricPoleTypeId(String pointElectricPoleTypeId) {
        this.pointElectricPoleTypeId = pointElectricPoleTypeId;
    }

    public int getPointElectricPoleTypeCount() {
        return pointElectricPoleTypeCount;
    }

    public void setPointElectricPoleTypeCount(int pointElectricPoleTypeCount) {
        this.pointElectricPoleTypeCount = pointElectricPoleTypeCount;
    }

    public String getPointLandForm() {
        return pointLandForm;
    }

    public void setPointLandForm(String pointLandForm) {
        this.pointLandForm = pointLandForm;
    }

    public String getPointNum() {
        return pointNum;
    }

    public void setPointNum(String pointNum) {
        this.pointNum = pointNum;
    }

    public Double getPointCoverDepth() {
        return pointCoverDepth;
    }

    public void setPointCoverDepth(Double pointCoverDepth) {
        this.pointCoverDepth = pointCoverDepth;
    }

    // KEEP METHODS - put your custom methods here

    public MapPoiEntity(String pointId, double pointLatitude, double pointLongitude, int pointType) {
        this.pointId = pointId;
        this.pointLatitude = pointLatitude;
        this.pointLongitude = pointLongitude;
        this.pointType = pointType;
    }

    public List<PointGalleryEntity> getPointGalleryLists() {
        return pointGalleryLists;
    }

    public void setPointGalleryLists(List<PointGalleryEntity> pointGalleryLists) {
        this.pointGalleryLists = pointGalleryLists;
    }

    @Override
    public String toString() {
        return "MapPoiEntity{" +
                "pointId='" + pointId + '\'' +
                ", pointProjId=" + pointProjId +
                ", pointUserId=" + pointUserId +
                ", pointEditType=" + pointEditType +
                ", pointType=" + pointType +
                ", pointLatitude=" + pointLatitude +
                ", pointLongitude=" + pointLongitude +
                ", pointName='" + pointName + '\'' +
                ", pointNote='" + pointNote + '\'' +
                ", pointRemoved=" + pointRemoved +
                ", pointNeedToUpload=" + pointNeedToUpload +
                ", pointUpdateDate=" + pointUpdateDate +
                ", pointLightingNum=" + pointLightingNum +
                ", pointPowerNum=" + pointPowerNum +
                ", pointConnectDoorNum=" + pointConnectDoorNum +
                ", pointTransformerTypeId='" + pointTransformerTypeId + '\'' +
                ", pointStatus=" + pointStatus +
                ", pointTowerTypeId='" + pointTowerTypeId + '\'' +
                ", pointGeologicalConditionsTypeId='" + pointGeologicalConditionsTypeId + '\'' +
                ", pointEquipmentInstallationTypeId='" + pointEquipmentInstallationTypeId + '\'' +
                ", pointElectricPoleTypeId='" + pointElectricPoleTypeId + '\'' +
                ", pointElectricPoleTypeCount=" + pointElectricPoleTypeCount +
                ", pointLandForm='" + pointLandForm + '\'' +
                ", pointNum='" + pointNum + '\'' +
                ", pointCoverDepth=" + pointCoverDepth +
                ", pointGalleryLists=" + pointGalleryLists +
                '}';
    }


    // KEEP METHODS END

}
