package com.hz.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "POINT_GALLERY_ENTITY".
 */
public class PointGalleryEntity implements java.io.Serializable {

    /** Not-null value. */
    private String imgId;
    /** Not-null value. */
    private String imgPointId;
    private String imgFrom;
    private String imgAddress;
    private int imgUploadProgress;
    private int imgRemoved;
    private boolean imgNeedToUpload;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PointGalleryEntity() {
    }

    public PointGalleryEntity(String imgId) {
        this.imgId = imgId;
    }

    public PointGalleryEntity(String imgId, String imgPointId, String imgFrom, String imgAddress, int imgUploadProgress, int imgRemoved, boolean imgNeedToUpload) {
        this.imgId = imgId;
        this.imgPointId = imgPointId;
        this.imgFrom = imgFrom;
        this.imgAddress = imgAddress;
        this.imgUploadProgress = imgUploadProgress;
        this.imgRemoved = imgRemoved;
        this.imgNeedToUpload = imgNeedToUpload;
    }

    /** Not-null value. */
    public String getImgId() {
        return imgId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgId(String imgId) {
        this.imgId = imgId;
    }

    /** Not-null value. */
    public String getImgPointId() {
        return imgPointId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgPointId(String imgPointId) {
        this.imgPointId = imgPointId;
    }

    public String getImgFrom() {
        return imgFrom;
    }

    public void setImgFrom(String imgFrom) {
        this.imgFrom = imgFrom;
    }

    public String getImgAddress() {
        return imgAddress;
    }

    public void setImgAddress(String imgAddress) {
        this.imgAddress = imgAddress;
    }

    public int getImgUploadProgress() {
        return imgUploadProgress;
    }

    public void setImgUploadProgress(int imgUploadProgress) {
        this.imgUploadProgress = imgUploadProgress;
    }

    public int getImgRemoved() {
        return imgRemoved;
    }

    public void setImgRemoved(int imgRemoved) {
        this.imgRemoved = imgRemoved;
    }

    public boolean getImgNeedToUpload() {
        return imgNeedToUpload;
    }

    public void setImgNeedToUpload(boolean imgNeedToUpload) {
        this.imgNeedToUpload = imgNeedToUpload;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "PointGalleryEntity{" +
                "imgId='" + imgId + '\'' +
                ", imgPointId='" + imgPointId + '\'' +
                ", imgFrom='" + imgFrom + '\'' +
                ", imgAddress='" + imgAddress + '\'' +
                ", imgRemoved=" + imgRemoved +
                ", imgNeedToUpload=" + imgNeedToUpload +
                '}';
    }
    // KEEP METHODS END

}
