package com.hz.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PROJECT_ENTITY".
 */
public class ProjectEntity implements java.io.Serializable {

    private long id;
    private String projectName;
    private String programmeName;
    private Integer projectLeader;
    private String cjsj;
    private Integer picId;
    private Integer scbz;
    private Integer projectCreator;
    private String status;
    private String projectNum;
    private Integer voltageType;
    private Integer terrainId;
    private Integer belongId;
    private Integer areaType;
    private Integer areaId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ProjectEntity() {
    }

    public ProjectEntity(long id) {
        this.id = id;
    }

    public ProjectEntity(long id, String projectName, String programmeName, Integer projectLeader, String cjsj, Integer picId, Integer scbz, Integer projectCreator, String status, String projectNum, Integer voltageType, Integer terrainId, Integer belongId, Integer areaType, Integer areaId) {
        this.id = id;
        this.projectName = projectName;
        this.programmeName = programmeName;
        this.projectLeader = projectLeader;
        this.cjsj = cjsj;
        this.picId = picId;
        this.scbz = scbz;
        this.projectCreator = projectCreator;
        this.status = status;
        this.projectNum = projectNum;
        this.voltageType = voltageType;
        this.terrainId = terrainId;
        this.belongId = belongId;
        this.areaType = areaType;
        this.areaId = areaId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getProgrammeName() {
        return programmeName;
    }

    public void setProgrammeName(String programmeName) {
        this.programmeName = programmeName;
    }

    public Integer getProjectLeader() {
        return projectLeader;
    }

    public void setProjectLeader(Integer projectLeader) {
        this.projectLeader = projectLeader;
    }

    public String getCjsj() {
        return cjsj;
    }

    public void setCjsj(String cjsj) {
        this.cjsj = cjsj;
    }

    public Integer getPicId() {
        return picId;
    }

    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    public Integer getScbz() {
        return scbz;
    }

    public void setScbz(Integer scbz) {
        this.scbz = scbz;
    }

    public Integer getProjectCreator() {
        return projectCreator;
    }

    public void setProjectCreator(Integer projectCreator) {
        this.projectCreator = projectCreator;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getProjectNum() {
        return projectNum;
    }

    public void setProjectNum(String projectNum) {
        this.projectNum = projectNum;
    }

    public Integer getVoltageType() {
        return voltageType;
    }

    public void setVoltageType(Integer voltageType) {
        this.voltageType = voltageType;
    }

    public Integer getTerrainId() {
        return terrainId;
    }

    public void setTerrainId(Integer terrainId) {
        this.terrainId = terrainId;
    }

    public Integer getBelongId() {
        return belongId;
    }

    public void setBelongId(Integer belongId) {
        this.belongId = belongId;
    }

    public Integer getAreaType() {
        return areaType;
    }

    public void setAreaType(Integer areaType) {
        this.areaType = areaType;
    }

    public Integer getAreaId() {
        return areaId;
    }

    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "ProjectEntity{" +
                "id=" + id +
                ", projectName='" + projectName + '\'' +
                ", programmeName='" + programmeName + '\'' +
                ", projectLeader=" + projectLeader +
                ", cjsj='" + cjsj + '\'' +
                ", picId=" + picId +
                ", scbz=" + scbz +
                ", projectCreator=" + projectCreator +
                ", status='" + status + '\'' +
                ", projectNum='" + projectNum + '\'' +
                ", voltageType=" + voltageType +
                ", terrainId=" + terrainId +
                ", belongId=" + belongId +
                '}';
    }
    // KEEP METHODS END

}
