package com.hz.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TRANSFORMER_TYPE".
 */
public class TransformerType implements java.io.Serializable {

    private long id;
    private String capacity;
    private String scbz;
    private java.util.Date cjsj;
    private java.util.Date updateDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TransformerType() {
    }

    public TransformerType(long id) {
        this.id = id;
    }

    public TransformerType(long id, String capacity, String scbz, java.util.Date cjsj, java.util.Date updateDate) {
        this.id = id;
        this.capacity = capacity;
        this.scbz = scbz;
        this.cjsj = cjsj;
        this.updateDate = updateDate;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getCapacity() {
        return capacity;
    }

    public void setCapacity(String capacity) {
        this.capacity = capacity;
    }

    public String getScbz() {
        return scbz;
    }

    public void setScbz(String scbz) {
        this.scbz = scbz;
    }

    public java.util.Date getCjsj() {
        return cjsj;
    }

    public void setCjsj(java.util.Date cjsj) {
        this.cjsj = cjsj;
    }

    public java.util.Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(java.util.Date updateDate) {
        this.updateDate = updateDate;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "TransformerType{" +
                "id=" + id +
                ", capacity='" + capacity + '\'' +
                ", scbz='" + scbz + '\'' +
                ", cjsj=" + cjsj +
                ", updateDate=" + updateDate +
                '}';
    }
    // KEEP METHODS END

}
